repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4  # Check for the latest version at https://github.com/astral-sh/ruff-pre-commit
    hooks:
      - id: ruff
        args: [--fix]  # Enables automatic fixing of issues
